// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2-3GHnPRNzDTDZRfS10wwFgGeaOusoF0',
    appId: '1:1018882869283:web:d00f6f2ccf1987a7dd4996',
    messagingSenderId: '1018882869283',
    projectId: 'nexprep-58b9d',
    authDomain: 'nexprep-58b9d.firebaseapp.com',
    storageBucket: 'nexprep-58b9d.firebasestorage.app',
    measurementId: 'G-FKHD459TCL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Yswp_xesyJtkUEOPiY-BF6Uybm2uGVI',
    appId: '1:1018882869283:android:a10c90d7de7ef073dd4996',
    messagingSenderId: '1018882869283',
    projectId: 'nexprep-58b9d',
    storageBucket: 'nexprep-58b9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsCuXHYFvfdXMPRDrZg1WF9NxpZ0nttiI',
    appId: '1:1018882869283:ios:324c6562317b18a3dd4996',
    messagingSenderId: '1018882869283',
    projectId: 'nexprep-58b9d',
    storageBucket: 'nexprep-58b9d.firebasestorage.app',
    iosClientId: '1018882869283-mbf49vutmuumus402m5pue9ska6b2vmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexprep',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsCuXHYFvfdXMPRDrZg1WF9NxpZ0nttiI',
    appId: '1:1018882869283:ios:324c6562317b18a3dd4996',
    messagingSenderId: '1018882869283',
    projectId: 'nexprep-58b9d',
    storageBucket: 'nexprep-58b9d.firebasestorage.app',
    iosClientId: '1018882869283-mbf49vutmuumus402m5pue9ska6b2vmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexprep',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2-3GHnPRNzDTDZRfS10wwFgGeaOusoF0',
    appId: '1:1018882869283:web:ef1af0cdb0c441a2dd4996',
    messagingSenderId: '1018882869283',
    projectId: 'nexprep-58b9d',
    authDomain: 'nexprep-58b9d.firebaseapp.com',
    storageBucket: 'nexprep-58b9d.firebasestorage.app',
    measurementId: 'G-6E1LJGR12R',
  );
}
